language: python
python:
  - "3.6"
cache: pip
install:
  - pip install pandas
  - pip install -e git+https://github.com/vispy/vispy#egg=vispy-dev
script:
  - python xplor/tests.py
  - python xplor/test_thomas.py